/**
 * Security policy for every response. Imported by astro.config.mjs, so keep it free of `astro:*` imports.
 *
 * - The Content Security Policy is generated by Astro, which hashes every script and stylesheet it emits,
 *   so scripts never need `'unsafe-inline'`. The config below only lists the extra sources and hashes.
 *   Astro serves it as an HTTP header for every page (adapter `staticHeaders`).
 * - SECURITY_HEADERS are attached to every route by integrations/security-headers.ts.
 *
 * Verified in a real browser by tests/e2e (no CSP violations on any page or interaction).
 */
import type { AstroUserConfig } from 'astro';
import { cspHash } from '../lib/csp.ts';
import { THEME_INIT_SCRIPT } from '../lib/theme.ts';

type CspConfig = Exclude<NonNullable<NonNullable<AstroUserConfig['security']>['csp']>, boolean>;

/** Cloudflare Turnstile (contact-form spam protection) loads a script and an iframe from here. */
const TURNSTILE_ORIGIN = 'https://challenges.cloudflare.com';

export const CSP: CspConfig = {
  algorithm: 'SHA-256',
  directives: [
    "default-src 'self'",
    "img-src 'self' data:",
    // `data:` covers tiny font subsets that Vite inlines into the stylesheet.
    "font-src 'self' data:",
    `connect-src 'self' ${TURNSTILE_ORIGIN}`,
    `frame-src ${TURNSTILE_ORIGIN}`,
    "object-src 'none'",
    "base-uri 'self'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    'upgrade-insecure-requests',
  ],
  scriptDirective: {
    resources: ["'self'", TURNSTILE_ORIGIN],
    // The pre-paint theme script must be inline; it is allowed by a hash of the same constant it is rendered from.
    hashes: [cspHash(THEME_INIT_SCRIPT)],
  },
  styleDirective: {
    // Stylesheets and <style> elements are hashed. Inline `style` *attributes* (per-element animation delays,
    // view-transition names, Shiki token colours) cannot be hashed, so they are allowed via `style-src-attr`.
    // Attribute styles cannot execute script, so this does not weaken script protection.
    resources: ["'self'", { resource: "'unsafe-inline'", kind: 'attribute' }],
  },
};

/** Headers applied to every response, static or on-demand. */
export const SECURITY_HEADERS: Record<string, string> = {
  // Add `; preload` only once the site is on an apex domain you control and is submitted to hstspreload.org.
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains',
  'X-Content-Type-Options': 'nosniff',
  'X-Frame-Options': 'DENY',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=(), payment=(), usb=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
};
